(require 'package)
(add-hook 'org-mode-hook 'org-indent-mode)
(add-hook 'org-mode-hook 'visual-line-mode)
(add-hook 'org-mode-hook (lambda()
			   (local-unset-key (kbd "C-<tab>"))))
	  (setq org-image-actual-width nil)
(provide 'init-org)
